development:
  password: ${THEME_PASSWORD}
  theme_id: ${THEMEID_PRODUCTION}
  store: ${THEME_STORE_URL}
staging:
  password: ${THEME_PASSWORD}
  theme_id: ${THEMEID_STAGING}
  store: ${THEME_STORE_URL}
